version: "3.9"

services:
  proxy:
    platform: linux/amd64
    build:
      context: ./squid
    volumes:
      - type: bind
        source: /var/lib/systemd/coredump/
        target: /tmp/coredump/
    ports:
      - 3128:3128
