version: "3.9"

services:
  proxy:
    build:
      context: ./squid
    ports:
      - 3128:3128
    depends_on:
      - icap

  icap:
    build:
      context: ./icap
    ports:
      - 13440:13440
