version: "3.9"

services:
  proxy:
    platform: linux/amd64
    build:
      context: ./squid
    volumes:
    - type: bind
      source: ${BIND_SOURCE:-/tmp}
      target: /tmp/coredump/
    ports:
      - 3128:3128
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined
